import os
from flask import Flask, jsonify, request, session
import queryDB as query

app = Flask(__name__, static_folder='./build', static_url_path='/')
app.secret_key = b'm\xb5\xe6\xef4\xb5\x02_\x8f\xe4\xffpw\xccu\xc4' # generated by os.urandom(16)

@app.route('/')
def index():
    # to be changed with login
    session['user_name'] = 'Ezron'
    return app.send_static_file('index.html')

@app.route('/addWorkout', methods=['POST'])
def update_ProgressDB():
    data = request.get_json()
    print(data)
    challengeName = data['challenge']
    file = data['file']
    caption = data['caption']
    userName = session['user_name']

    # call function to UPDATE db Progress
    query.updateProg(userName, challengeName)
    if file != '':
        # call function to UPDATE db Photo, Caption, username
        newCap = query.insertPhoto(file, caption, userName)
        result = {'new caption': newCap}
    else:
        result = {'new caption': ''}
    return(result)

@app.route('/progressUpdated', methods=['GET'])
def get_updatedProgress():
    # call function to SELECT from db
    newProgress = 'function call goes here'
    result = {'progress' : newProgress}
    return jsonify(result)
#-------------------------------------------------------------------------------

# if __name__ == '__main__':
#     app.run(host='0.0.0.0', debug=False, port=os.environ.get('PORT', 80))
